name: SkCord
version: '3.4-RELEASE'

api-version: 1.13

main: ovh.fedox.skcord.SkCord
depend:
  - Skript
authors: [ Fedox ]
description: Send discord webhooks with Skript!

libraries:
  - com.fasterxml.jackson.core:jackson-databind:2.15.2
  - org.jetbrains:annotations:24.0.0

commands:
  skcord:
